"""add_email_submission_fields_to_user_table

Revision ID: 3c964eefc0e6
Revises: a403e310e7b5
Create Date: 2025-05-31 16:44:35.217245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# sqlalchemy.dialects.postgresql.UUID was used in the previous migration,
# but DateTime, String, Boolean are standard sa types.

# revision identifiers, used by Alembic.
revision: str = '3c964eefc0e6'
down_revision: Union[str, None] = 'a403e310e7b5' # Points to the manual user table creation
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('submitted_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_submitted_email'), 'user', ['submitted_email'], unique=False)

    op.add_column('user', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=True)

    op.add_column('user', sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verification_token_expires_at')

    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_column('user', 'email_verification_token')

    op.drop_index(op.f('ix_user_submitted_email'), table_name='user')
    op.drop_column('user', 'submitted_email')
    # ### end Alembic commands ###
